name: Full Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    secrets:
      ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
      ANDROID_ALIAS: ${{ secrets.ANDROID_ALIAS }}
      ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    with:
      upload-artifact: true
      publish-release: false
